# Use the official Node.js base image
FROM node:latest as build

# Set the working directory in the container
WORKDIR /build

# Copy package.json and package-lock.json to the working directory
COPY package.json package.json
COPY yarn.lock yarn.lock

# Install the dependencies
RUN yarn install --production=false

# Copy the entire project directory to the working directory
COPY . .

# Build the React app
RUN npm run build

# Use a lightweight web server to serve the static files
#FROM nginx:latest
FROM nginx:alpine
WORKDIR /var/www/html

# Copy the static files generated by the React build
COPY --from=build build/build /usr/share/nginx/html

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
