export const bookseriesWorks = {
    image_attr: null,
    id: 5,
    image_src: null,
    orig_name: null,
    important: false,
    works: [
        {
            imported_string:
                "\n<b>Merihevoset</b>. Aavehevoset 1. (Sea Horses, 2003). Suom Veera Saarelainen. Kustannus Oy Jalava 2004. [nF].",
            id: 5043.0,
            authors: [
                {
                    imported_string: null,
                    nationality: "Iso-Britannia",
                    image_attr: "",
                    other_names: null,
                    id: 3023.0,
                    image_src: null,
                    last_name: "Cooper",
                    fullname: "",
                    bio: null,
                    alt_name: "Louise Cooper",
                    workcount: 4.0,
                    first_name: "Louise",
                    dod: 2009.0,
                    roles: ["Kirjoittaja"],
                    name: "Cooper, Louise",
                    storycount: 0.0,
                    dob: 1952.0,
                    bio_src: "",
                },
            ],
            subtitle: "",
            editions: [
                {
                    imported_string:
                        "\n<b>Merihevoset</b>. Aavehevoset 1. (Sea Horses, 2003). Suom Veera Saarelainen. Kustannus Oy Jalava 2004. [nF].",
                    images: [],
                    id: 5844,
                    subtitle: "",
                    pubyear: 2004,
                    size: null,
                    printedin: null,
                    translators: [
                        {
                            imported_string:
                                "\n\n2.laitos: <b>Ozin kapinalliset</b>. Kuvittanut Petri Hiltunen. Ihmemaa Oz 2. Suom Veera Saarelainen. Art House 2002.",
                            nationality: "Suomi",
                            image_attr: "",
                            other_names: null,
                            id: 2751.0,
                            image_src: null,
                            last_name: "Saarelainen",
                            fullname: "",
                            bio: null,
                            alt_name: "Veera Saarelainen",
                            workcount: 0.0,
                            first_name: "Veera",
                            dod: null,
                            roles: ["Kääntäjä"],
                            name: "Saarelainen, Veera",
                            storycount: 0.0,
                            dob: null,
                            bio_src: "",
                        },
                    ],
                    pages: null,
                    publisher: { name: "Jalava", id: 110 },
                    misc: "",
                    version: null,
                    pubseriesnum: null,
                    dustcover: 1,
                    coll_info: "",
                    editors: [],
                    coverimage: 1,
                    isbn: "",
                    title: "Merihevoset",
                    editionnum: 1,
                },
            ],
            author_str: "Cooper, Louise",
            orig_title: "Sea Horses",
            pubyear: 2003,
            title: "Merihevoset",
            descr_attr: null,
            bookseriesnum: "1",
            misc: "",
            bookseries: {
                image_attr: null,
                id: 5,
                image_src: null,
                orig_name: null,
                important: false,
                works: [
                    {
                        imported_string:
                            "\n<b>Merihevoset</b>. Aavehevoset 1. (Sea Horses, 2003). Suom Veera Saarelainen. Kustannus Oy Jalava 2004. [nF].",
                        id: 5043,
                        subtitle: "",
                        orig_title: "Sea Horses",
                        author_str: "Cooper, Louise",
                        pubyear: 2003,
                        title: "Merihevoset",
                        descr_attr: null,
                        bookseriesnum: "1",
                        misc: "",
                        bookseriesorder: 1,
                        description: null,
                    },
                    {
                        imported_string:
                            "\n\n<b>Talismaani</b>. Aavehevoset 2. (The Talisman, 2004). Suom Sari Kare. Kustannus Oy Jalava 2005. [nF].",
                        id: 5045,
                        subtitle: "",
                        orig_title: "The Talisman",
                        author_str: "Cooper, Louise",
                        pubyear: 2004,
                        title: "Talismaani",
                        descr_attr: null,
                        bookseriesnum: "2",
                        misc: "",
                        bookseriesorder: 2,
                        description: null,
                    },
                    {
                        imported_string:
                            "\n\n<b>Nouseva myrsky</b>. Aavehevoset 3. (Gathering Storm, 2004). Suom Sari Kare. Kustannus Oy Jalava 2006. [nF].",
                        id: 5044,
                        subtitle: "",
                        orig_title: "Gathering Storm",
                        author_str: "Cooper, Louise",
                        pubyear: 2004,
                        title: "Nouseva myrsky",
                        descr_attr: null,
                        bookseriesnum: "3",
                        misc: "",
                        bookseriesorder: 3,
                        description: null,
                    },
                    {
                        imported_string:
                            "\n\n<b>Viimeinen salaisuus</b>. Aavehevoset 4. (The Last Secret, 2006). Suom Sari Kare. Kustannus Oy Jalava 2007. [nF].",
                        id: 5046,
                        subtitle: "",
                        orig_title: "The Last Secret",
                        author_str: "Cooper, Louise",
                        pubyear: 2006,
                        title: "Viimeinen salaisuus",
                        descr_attr: null,
                        bookseriesnum: "4",
                        misc: "",
                        bookseriesorder: 4,
                        description: null,
                    },
                ],
                name: "Aavehevoset",
            },
            bookseriesorder: 1,
            genres: [{ abbr: "nF", name: "Nuorten fantasia", id: 8 }],
            description: null,
        },
        {
            imported_string:
                "\n\n<b>Talismaani</b>. Aavehevoset 2. (The Talisman, 2004). Suom Sari Kare. Kustannus Oy Jalava 2005. [nF].",
            id: 5045.0,
            authors: [
                {
                    imported_string: null,
                    nationality: "Iso-Britannia",
                    image_attr: "",
                    other_names: null,
                    id: 3023.0,
                    image_src: null,
                    last_name: "Cooper",
                    fullname: "",
                    bio: null,
                    alt_name: "Louise Cooper",
                    workcount: 4.0,
                    first_name: "Louise",
                    dod: 2009.0,
                    roles: ["Kirjoittaja"],
                    name: "Cooper, Louise",
                    storycount: 0.0,
                    dob: 1952.0,
                    bio_src: "",
                },
            ],
            subtitle: "",
            editions: [
                {
                    imported_string:
                        "\n\n<b>Talismaani</b>. Aavehevoset 2. (The Talisman, 2004). Suom Sari Kare. Kustannus Oy Jalava 2005. [nF].",
                    images: [],
                    id: 5846,
                    subtitle: "",
                    pubyear: 2005,
                    size: null,
                    printedin: null,
                    translators: [
                        {
                            imported_string:
                                "\n\n<b>Kaaoskirous</b>. Pappiskvintetti - osa 5. (Forgotten Realms: The Chaos Curse, 1994). Suom Sari Kare. Kustannus Oy Jalava 2006. [F].",
                            nationality: "Suomi",
                            image_attr: "",
                            other_names: null,
                            id: 616.0,
                            image_src: null,
                            last_name: "Kare",
                            fullname: "",
                            bio: null,
                            alt_name: "Sari Kare",
                            workcount: 0.0,
                            first_name: "Sari",
                            dod: null,
                            roles: ["Kääntäjä"],
                            name: "Kare, Sari",
                            storycount: 0.0,
                            dob: null,
                            bio_src: "",
                        },
                    ],
                    pages: null,
                    publisher: { name: "Jalava", id: 110 },
                    misc: "",
                    version: null,
                    pubseriesnum: null,
                    dustcover: 1,
                    coll_info: "",
                    editors: [],
                    coverimage: 1,
                    isbn: "",
                    title: "Talismaani",
                    editionnum: 1,
                },
            ],
            author_str: "Cooper, Louise",
            orig_title: "The Talisman",
            pubyear: 2004,
            title: "Talismaani",
            descr_attr: null,
            bookseriesnum: "2",
            misc: "",
            bookseries: {
                image_attr: null,
                id: 5,
                image_src: null,
                orig_name: null,
                important: false,
                works: [
                    {
                        imported_string:
                            "\n<b>Merihevoset</b>. Aavehevoset 1. (Sea Horses, 2003). Suom Veera Saarelainen. Kustannus Oy Jalava 2004. [nF].",
                        id: 5043,
                        subtitle: "",
                        orig_title: "Sea Horses",
                        author_str: "Cooper, Louise",
                        pubyear: 2003,
                        title: "Merihevoset",
                        descr_attr: null,
                        bookseriesnum: "1",
                        misc: "",
                        bookseriesorder: 1,
                        description: null,
                    },
                    {
                        imported_string:
                            "\n\n<b>Talismaani</b>. Aavehevoset 2. (The Talisman, 2004). Suom Sari Kare. Kustannus Oy Jalava 2005. [nF].",
                        id: 5045,
                        subtitle: "",
                        orig_title: "The Talisman",
                        author_str: "Cooper, Louise",
                        pubyear: 2004,
                        title: "Talismaani",
                        descr_attr: null,
                        bookseriesnum: "2",
                        misc: "",
                        bookseriesorder: 2,
                        description: null,
                    },
                    {
                        imported_string:
                            "\n\n<b>Nouseva myrsky</b>. Aavehevoset 3. (Gathering Storm, 2004). Suom Sari Kare. Kustannus Oy Jalava 2006. [nF].",
                        id: 5044,
                        subtitle: "",
                        orig_title: "Gathering Storm",
                        author_str: "Cooper, Louise",
                        pubyear: 2004,
                        title: "Nouseva myrsky",
                        descr_attr: null,
                        bookseriesnum: "3",
                        misc: "",
                        bookseriesorder: 3,
                        description: null,
                    },
                    {
                        imported_string:
                            "\n\n<b>Viimeinen salaisuus</b>. Aavehevoset 4. (The Last Secret, 2006). Suom Sari Kare. Kustannus Oy Jalava 2007. [nF].",
                        id: 5046,
                        subtitle: "",
                        orig_title: "The Last Secret",
                        author_str: "Cooper, Louise",
                        pubyear: 2006,
                        title: "Viimeinen salaisuus",
                        descr_attr: null,
                        bookseriesnum: "4",
                        misc: "",
                        bookseriesorder: 4,
                        description: null,
                    },
                ],
                name: "Aavehevoset",
            },
            bookseriesorder: 2,
            genres: [{ abbr: "nF", name: "Nuorten fantasia", id: 8 }],
            description: null,
        },
        {
            imported_string:
                "\n\n<b>Nouseva myrsky</b>. Aavehevoset 3. (Gathering Storm, 2004). Suom Sari Kare. Kustannus Oy Jalava 2006. [nF].",
            id: 5044.0,
            authors: [
                {
                    imported_string: null,
                    nationality: "Iso-Britannia",
                    image_attr: "",
                    other_names: null,
                    id: 3023.0,
                    image_src: null,
                    last_name: "Cooper",
                    fullname: "",
                    bio: null,
                    alt_name: "Louise Cooper",
                    workcount: 4.0,
                    first_name: "Louise",
                    dod: 2009.0,
                    roles: ["Kirjoittaja"],
                    name: "Cooper, Louise",
                    storycount: 0.0,
                    dob: 1952.0,
                    bio_src: "",
                },
            ],
            subtitle: "",
            editions: [
                {
                    imported_string:
                        "\n\n<b>Nouseva myrsky</b>. Aavehevoset 3. (Gathering Storm, 2004). Suom Sari Kare. Kustannus Oy Jalava 2006. [nF].",
                    images: [],
                    id: 5845,
                    subtitle: "",
                    pubyear: 2006,
                    size: null,
                    printedin: null,
                    translators: [
                        {
                            imported_string:
                                "\n\n<b>Kaaoskirous</b>. Pappiskvintetti - osa 5. (Forgotten Realms: The Chaos Curse, 1994). Suom Sari Kare. Kustannus Oy Jalava 2006. [F].",
                            nationality: "Suomi",
                            image_attr: "",
                            other_names: null,
                            id: 616.0,
                            image_src: null,
                            last_name: "Kare",
                            fullname: "",
                            bio: null,
                            alt_name: "Sari Kare",
                            workcount: 0.0,
                            first_name: "Sari",
                            dod: null,
                            roles: ["Kääntäjä"],
                            name: "Kare, Sari",
                            storycount: 0.0,
                            dob: null,
                            bio_src: "",
                        },
                    ],
                    pages: null,
                    publisher: { name: "Jalava", id: 110 },
                    misc: "",
                    version: null,
                    pubseriesnum: null,
                    dustcover: 1,
                    coll_info: "",
                    editors: [],
                    coverimage: 1,
                    isbn: "",
                    title: "Nouseva myrsky",
                    editionnum: 1,
                },
            ],
            author_str: "Cooper, Louise",
            orig_title: "Gathering Storm",
            pubyear: 2004,
            title: "Nouseva myrsky",
            descr_attr: null,
            bookseriesnum: "3",
            misc: "",
            bookseries: {
                image_attr: null,
                id: 5,
                image_src: null,
                orig_name: null,
                important: false,
                works: [
                    {
                        imported_string:
                            "\n<b>Merihevoset</b>. Aavehevoset 1. (Sea Horses, 2003). Suom Veera Saarelainen. Kustannus Oy Jalava 2004. [nF].",
                        id: 5043,
                        subtitle: "",
                        orig_title: "Sea Horses",
                        author_str: "Cooper, Louise",
                        pubyear: 2003,
                        title: "Merihevoset",
                        descr_attr: null,
                        bookseriesnum: "1",
                        misc: "",
                        bookseriesorder: 1,
                        description: null,
                    },
                    {
                        imported_string:
                            "\n\n<b>Talismaani</b>. Aavehevoset 2. (The Talisman, 2004). Suom Sari Kare. Kustannus Oy Jalava 2005. [nF].",
                        id: 5045,
                        subtitle: "",
                        orig_title: "The Talisman",
                        author_str: "Cooper, Louise",
                        pubyear: 2004,
                        title: "Talismaani",
                        descr_attr: null,
                        bookseriesnum: "2",
                        misc: "",
                        bookseriesorder: 2,
                        description: null,
                    },
                    {
                        imported_string:
                            "\n\n<b>Nouseva myrsky</b>. Aavehevoset 3. (Gathering Storm, 2004). Suom Sari Kare. Kustannus Oy Jalava 2006. [nF].",
                        id: 5044,
                        subtitle: "",
                        orig_title: "Gathering Storm",
                        author_str: "Cooper, Louise",
                        pubyear: 2004,
                        title: "Nouseva myrsky",
                        descr_attr: null,
                        bookseriesnum: "3",
                        misc: "",
                        bookseriesorder: 3,
                        description: null,
                    },
                    {
                        imported_string:
                            "\n\n<b>Viimeinen salaisuus</b>. Aavehevoset 4. (The Last Secret, 2006). Suom Sari Kare. Kustannus Oy Jalava 2007. [nF].",
                        id: 5046,
                        subtitle: "",
                        orig_title: "The Last Secret",
                        author_str: "Cooper, Louise",
                        pubyear: 2006,
                        title: "Viimeinen salaisuus",
                        descr_attr: null,
                        bookseriesnum: "4",
                        misc: "",
                        bookseriesorder: 4,
                        description: null,
                    },
                ],
                name: "Aavehevoset",
            },
            bookseriesorder: 3,
            genres: [{ abbr: "nF", name: "Nuorten fantasia", id: 8 }],
            description: null,
        },
        {
            imported_string:
                "\n\n<b>Viimeinen salaisuus</b>. Aavehevoset 4. (The Last Secret, 2006). Suom Sari Kare. Kustannus Oy Jalava 2007. [nF].",
            id: 5046.0,
            authors: [
                {
                    imported_string: null,
                    nationality: "Iso-Britannia",
                    image_attr: "",
                    other_names: null,
                    id: 3023.0,
                    image_src: null,
                    last_name: "Cooper",
                    fullname: "",
                    bio: null,
                    alt_name: "Louise Cooper",
                    workcount: 4.0,
                    first_name: "Louise",
                    dod: 2009.0,
                    roles: ["Kirjoittaja"],
                    name: "Cooper, Louise",
                    storycount: 0.0,
                    dob: 1952.0,
                    bio_src: "",
                },
            ],
            subtitle: "",
            editions: [
                {
                    imported_string:
                        "\n\n<b>Viimeinen salaisuus</b>. Aavehevoset 4. (The Last Secret, 2006). Suom Sari Kare. Kustannus Oy Jalava 2007. [nF].",
                    images: [],
                    id: 5847,
                    subtitle: "",
                    pubyear: 2007,
                    size: null,
                    printedin: null,
                    translators: [
                        {
                            imported_string:
                                "\n\n<b>Kaaoskirous</b>. Pappiskvintetti - osa 5. (Forgotten Realms: The Chaos Curse, 1994). Suom Sari Kare. Kustannus Oy Jalava 2006. [F].",
                            nationality: "Suomi",
                            image_attr: "",
                            other_names: null,
                            id: 616.0,
                            image_src: null,
                            last_name: "Kare",
                            fullname: "",
                            bio: null,
                            alt_name: "Sari Kare",
                            workcount: 0.0,
                            first_name: "Sari",
                            dod: null,
                            roles: ["Kääntäjä"],
                            name: "Kare, Sari",
                            storycount: 0.0,
                            dob: null,
                            bio_src: "",
                        },
                    ],
                    pages: null,
                    publisher: { name: "Jalava", id: 110 },
                    misc: "",
                    version: null,
                    pubseriesnum: null,
                    dustcover: 1,
                    coll_info: "",
                    editors: [],
                    coverimage: 1,
                    isbn: "",
                    title: "Viimeinen salaisuus",
                    editionnum: 1,
                },
            ],
            author_str: "Cooper, Louise",
            orig_title: "The Last Secret",
            pubyear: 2006,
            title: "Viimeinen salaisuus",
            descr_attr: null,
            bookseriesnum: "4",
            misc: "",
            bookseries: {
                image_attr: null,
                id: 5,
                image_src: null,
                orig_name: null,
                important: false,
                works: [
                    {
                        imported_string:
                            "\n<b>Merihevoset</b>. Aavehevoset 1. (Sea Horses, 2003). Suom Veera Saarelainen. Kustannus Oy Jalava 2004. [nF].",
                        id: 5043,
                        subtitle: "",
                        orig_title: "Sea Horses",
                        author_str: "Cooper, Louise",
                        pubyear: 2003,
                        title: "Merihevoset",
                        descr_attr: null,
                        bookseriesnum: "1",
                        misc: "",
                        bookseriesorder: 1,
                        description: null,
                    },
                    {
                        imported_string:
                            "\n\n<b>Talismaani</b>. Aavehevoset 2. (The Talisman, 2004). Suom Sari Kare. Kustannus Oy Jalava 2005. [nF].",
                        id: 5045,
                        subtitle: "",
                        orig_title: "The Talisman",
                        author_str: "Cooper, Louise",
                        pubyear: 2004,
                        title: "Talismaani",
                        descr_attr: null,
                        bookseriesnum: "2",
                        misc: "",
                        bookseriesorder: 2,
                        description: null,
                    },
                    {
                        imported_string:
                            "\n\n<b>Nouseva myrsky</b>. Aavehevoset 3. (Gathering Storm, 2004). Suom Sari Kare. Kustannus Oy Jalava 2006. [nF].",
                        id: 5044,
                        subtitle: "",
                        orig_title: "Gathering Storm",
                        author_str: "Cooper, Louise",
                        pubyear: 2004,
                        title: "Nouseva myrsky",
                        descr_attr: null,
                        bookseriesnum: "3",
                        misc: "",
                        bookseriesorder: 3,
                        description: null,
                    },
                    {
                        imported_string:
                            "\n\n<b>Viimeinen salaisuus</b>. Aavehevoset 4. (The Last Secret, 2006). Suom Sari Kare. Kustannus Oy Jalava 2007. [nF].",
                        id: 5046,
                        subtitle: "",
                        orig_title: "The Last Secret",
                        author_str: "Cooper, Louise",
                        pubyear: 2006,
                        title: "Viimeinen salaisuus",
                        descr_attr: null,
                        bookseriesnum: "4",
                        misc: "",
                        bookseriesorder: 4,
                        description: null,
                    },
                ],
                name: "Aavehevoset",
            },
            bookseriesorder: 4,
            genres: [{ abbr: "nF", name: "Nuorten fantasia", id: 8 }],
            description: null,
        },
    ],
    name: "Aavehevoset",
};
