const countryMap: { [key: string]: string } = {
    "Alankomaat": "NL",
    "Argentiina": "AR",
    "Australia": "AU",
    "Belgia": "BE",
    "Brasilia": "BR",
    "Chile": "CL",
    "Egypti": "EG",
    "Espanja": "ES",
    "Etelä-Afrikka": "ZA",
    "Georgia": "GE",
    "Hollanti": "NL",  // Alternative name for Alankomaat
    "Indonesia": "ID",
    "Intia": "IN",
    "Iran": "IR",
    "Irlanti": "IE",
    "Islanti": "IS",
    "Iso-Britannia": "GB",
    "Israel": "IL",
    "Italia": "IT",
    "Itävalta": "AT",
    "Japani": "JP",
    "Kanada": "CA",
    "Kenia": "KE",
    "Kiina": "CN",
    "Kolumbia": "CO",
    "Kreikka": "GR",
    "Kuuba": "CU",
    "Latvia": "LV",
    "Libanon": "LB",
    "Malesia": "MY",
    "Meksiko": "MX",
    "Neuvostoliitto": "SU",  // Historical
    "Nigeria": "NG",
    "Norja": "NO",
    "Portugali": "PT",
    "Puola": "PL",
    "Ranska": "FR",
    "Romania": "RO",
    "Ruotsi": "SE",
    "Saksa": "DE",
    "Serbia": "RS",
    "Singapore": "SG",
    "Suomi": "FI",
    "Sveitsi": "CH",
    "Taiwan": "TW",
    "Tanska": "DK",
    "Tsekki": "CZ",
    "Tsekkoslovakia": "CS",  // Historical
    "Turkki": "TR",
    "Unkari": "HU",
    "Uruguay": "UY",
    "Uusi-Seelanti": "NZ",
    "Venezuela": "VE",
    "Venäjä": "RU",
    "Viro": "EE",
    "Yhdysvallat": "US",
    "Yhdistynyt kuningaskunta": "GB",  // Alternative name for Iso-Britannia
    "Zimbabwe": "ZW",
};

export const getCountryCode = (finnishName: string): string => {
    return countryMap[finnishName] || "UNKNOWN";
};